# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{prawn_commander}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = %q{2010-06-25}
  s.description = %q{Command center for prawn commands that enable logging commands before or without executing them}
  s.email = %q{kmandrup@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/prawn_commander.rb",
     "prawn_commander.gemspec",
     "spec/matcher/command_matcher.rb",
     "spec/prawn_commander_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/kristianmandrup/prawn_commander}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Command center for prawn commands that enable logging}
  s.test_files = [
    "spec/matcher/command_matcher.rb",
     "spec/prawn_commander_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.0.0.beta13"])
      s.add_runtime_dependency(%q<prawn>, [">= 0.8.4"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0.0.beta13"])
      s.add_dependency(%q<prawn>, [">= 0.8.4"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0.0.beta13"])
    s.add_dependency(%q<prawn>, [">= 0.8.4"])
  end
end

